config:
    # general
    seed: 123
    data_folder_path: './data/processed/'
    lead1: null
    lead2: null
    # training
    batch_size: 32
    n_epochs: 10
    # architecture - to be changed later and pushed out towards tuning
    init_token: null
    input_dimension: 12
    output_dimension: 12              
    hidden_dimmension:  64           # d_model (int) – the number of expected features in the input (required)???
    attention_heads: null             # number of attention heads, if None then d_model//64
    encoder_number_of_layers: 4
    decoder_number_of_layers: 4
    dropout: 0.5
    clip: 1
    window: 500 
    positional_encodings: False
    stride: 0.75
    n_iters:  50                      # plot intermediate results on validation every <n_iters> steps
    num_plots: 5
    model_type: "encoder"
    saving_path: './models/12leads'
