config:
    # general
    seed: 123
    data_folder_path: './data/processed/'
    # training
    batch_size: 32
    n_epochs: 30
    # architecture - to be changed later and pushed out towards tuning
    init_token: null
    input_dimension: 12
    output_dimension: 12              
    hidden_dimmension:  64           # d_model (int) – the number of expected features in the input (required)???
    attention_heads: null             # number of attention heads, if None then d_model//64
    encoder_number_of_layers: 8
    decoder_number_of_layers: 8
    dropout: 0.4
    clip: 1
    window: 450 
    train_by_sample: 1
    positional_encodings: False
    stride: 0.75
    n_iters:  null                      # plot intermediate results on validation every <n_iters> steps
    num_plots: 5
    model_type: "encoder"
    saving_path: './models/exp4-base-version-with-train-by-sample-window-450'
    plot_saving_path: './plots/exp4-base-version-with-train-by-sample-window-450'
